default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: gmoreno
  password: 123456

development:
  <<: *default
  database: db/EscuelaDigital

test:
  <<: *default
  database: db/test.EscuelaDigital

production:
  <<: *default
  database: db/production.EscuelaDigital
