default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: gmoreno
  password: 123456

development:
  <<: *default
  database: dev/escueladigital

test:
  <<: *default
  database: test/escueladigital

production:
  <<: *default
  database: production/escueladigital
